/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica8;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;

/**
 *
 * @author danint
 */
public class Practica8 extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();
    JFileChooser saveFC = new JFileChooser();
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg");
    Boolean imagenOpened = false;
    VentanaInterna vI;
    
    class myListener implements ComponentListener{

        @Override
        public void componentResized(ComponentEvent e) {
            if(escritorio.getAllFrames() != null){
                for(JInternalFrame internalFrame: escritorio.getAllFrames()){
                    recoloca(internalFrame);
                }
            }
            
        }
        private void recoloca(JInternalFrame internalFrame){
            if(internalFrame.getX()> escritorio.getX() + escritorio.getWidth() || 
                    internalFrame.getY()> escritorio.getY() + escritorio.getHeight()){

                internalFrame.setLocation(new Point(escritorio.getX()+escritorio.getWidth()/2 - internalFrame.getWidth()/2,
                        escritorio.getY()+escritorio.getHeight()/2- internalFrame.getHeight()/2 + 35));
            }
        }

        @Override
        public void componentMoved(ComponentEvent e) {
        }

        @Override
        public void componentShown(ComponentEvent e) {
        }

        @Override
        public void componentHidden(ComponentEvent e) {
        }   
    }
    class closeListener implements WindowListener{

        @Override
        public void windowOpened(WindowEvent e) {
        }

        @Override
        public void windowClosing(WindowEvent e) {
           
            if(JOptionPane.showConfirmDialog(escritorio,
                    "¿Seguro que desea cerrar la aplicación?","Confirmación de cerrado",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            dispose();
            } 
        }

        @Override
        public void windowClosed(WindowEvent e) {
        }

        @Override
        public void windowIconified(WindowEvent e) {
        }

        @Override
        public void windowDeiconified(WindowEvent e) {
        }

        @Override
        public void windowActivated(WindowEvent e) {
        }

        @Override
        public void windowDeactivated(WindowEvent e) {
        }
        
    }
    /**
     * Creates new form Practica8
     */
    public Practica8() {
        nu.pattern.OpenCV.loadShared();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
        fc.addChoosableFileFilter(filtro);
        addComponentListener(new myListener());
        addWindowListener(new closeListener());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        umbralizarBtnDialog = new javax.swing.JButton();
        umbral = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Ficheros = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        UmbralizarMenu = new javax.swing.JMenuItem();

        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialog.setName("dialogo"); // NOI18N
        dialog.setPreferredSize(new java.awt.Dimension(200, 150));

        umbralizarBtnDialog.setText("Umbralizar");
        umbralizarBtnDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umbralizarBtnDialogActionPerformed(evt);
            }
        });

        jLabel1.setText("Umbral:");

        jDesktopPane1.setLayer(umbralizarBtnDialog, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(umbral, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(umbral))
                    .addComponent(umbralizarBtnDialog))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(umbral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(umbralizarBtnDialog)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        dialog.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setText("Alejandro Santana Amador");

        jLabel3.setText("Daniel Naranjo Torres");

        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        Ficheros.setText("Ficheros");

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Ficheros.add(Abrir);

        jMenuBar1.add(Ficheros);

        Edicion.setText("Edición");

        UmbralizarMenu.setText("Umbralizar");
        UmbralizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmbralizarMenuActionPerformed(evt);
            }
        });
        Edicion.add(UmbralizarMenu);

        jMenuBar1.add(Edicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            imagenOpened=true;
            try {
                for(JInternalFrame internalFrame: escritorio.getAllFrames()){
                internalFrame.dispose();
            }
                vI = new VentanaInterna();
                escritorio.add(vI);
                vI.setImg(fichero.getAbsolutePath());
                vI.setTitle(fichero.getName()); 
                vI.setLocation(new Point(escritorio.getX()+escritorio.getWidth()/2 - vI.getWidth()/2,
                escritorio.getY()+escritorio.getHeight()/2 - vI.getHeight()/2 + 10));
                
            } catch (IOException ex) {
                Logger.getLogger(Practica8.class.getName()).log(Level.SEVERE, null, ex);
            }
            repaint();
        }    
    }//GEN-LAST:event_AbrirActionPerformed

    private void umbralizarBtnDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umbralizarBtnDialogActionPerformed
        String umbralTxt = umbral.getText();
        if(umbralTxt.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un umbral","Selecciona un umbral",2);
        }else if(!imagenOpened){
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una imagen","Selecciona una imagen",2);
        }else{
            vI = new VentanaInterna();
            escritorio.add(vI);
            vI.setLocation(new Point(escritorio.getX()+escritorio.getWidth()/2 - vI.getWidth()/2,
                escritorio.getY()+escritorio.getHeight()/2 - vI.getHeight()/2 + 10));
            vI.umbralizar(Integer.parseInt(umbralTxt));
            vI.toFront();
            repaint();
        }

    }//GEN-LAST:event_umbralizarBtnDialogActionPerformed

    private void UmbralizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmbralizarMenuActionPerformed
        dialog.setVisible(true);
        dialog.setSize(new Dimension(200,115));
        dialog.setLocation(new Point(this.getX()+this.getWidth()/2 - dialog.getWidth()/2,
                this.getY()+this.getHeight()/2 - dialog.getHeight()/2));
        dialog.setTitle("Umbralizar");
        dialog.setResizable(false);
        dialog.toFront();
    }//GEN-LAST:event_UmbralizarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenu Ficheros;
    private javax.swing.JMenuItem UmbralizarMenu;
    private javax.swing.JDialog dialog;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField umbral;
    private javax.swing.JButton umbralizarBtnDialog;
    // End of variables declaration//GEN-END:variables
}
